Controllers/HomeController.cs
using Carreno_Financial_Portal.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Carreno_Financial_Portal.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            ViewBag.AccountType = new SelectList(db.BankAccountTypes, "Id", "Type");
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/HouseholdsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Carreno_Financial_Portal.Helpers;
using Carreno_Financial_Portal.Models;
using Microsoft.AspNet.Identity;
using Carreno_Financial_Portal.Extensions;
using System.Threading.Tasks;

namespace Carreno_Financial_Portal.Controllers
{
    [Authorize]
    public class HouseholdsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private RoleHelper roleHelper = new RoleHelper(); 

        
        public ActionResult Dashboard()
        {
            var houseId = db.Users.Find(User.Identity.GetUserId()).HouseholdId;
            var house = db.Households.Include(h => h.BankAccounts).Include(h => h.Notifications).FirstOrDefault(h => h.Id == houseId);



            //Setup the neccessary data for wizard
            ViewBag.AccountType = new SelectList(db.BankAccountTypes, "Id", "Type");
            




            return View(house);
        }

        // GET: Households
        public ActionResult Index()
        {
            return View(db.Households.ToList());
        }

        // GET: Households/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Household household = db.Households.Find(id);
            if (household == null)
            {
                return HttpNotFound();
            }
            return View(household);
        }

        // GET: Households/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Households/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(string houseName, string greeting, string bankName, int accountType, string startingBalance, string warningBalance, string categoryName, string itemName)
        {
            //var newHouse = new Household
            //{
            //    Created = DateTime.Now,
            //};
            //if (ModelState.IsValid)
            //{
            //    db.Households.Add(household);
            //    db.SaveChanges();



            //}

            var newHouse = new Household 
            { 
                Created = DateTime.Now,
                Name = houseName, 
                Greeting = greeting 
            };

            db.Households.Add(newHouse);
            db.SaveChanges();
            //After creating a new House we need to do the following actions
            //Update the Users record to include the new household Id
            var user = db.Users.Find(User.Identity.GetUserId());
            user.HouseholdId = newHouse.Id;

            //Assign this user to the role of owner
            roleHelper.AddUserToRole(user.Id, "Owner");

            //Call the programmatic rauthorize extension method
            await HttpContextBaseExtension.RefreshAuthentication(HttpContext, user);

            var newBank = new BankAccount
            {
                HouseholdId = newHouse.Id,
                BankAccountTypeId = accountType,
                Created = DateTime.Now,
                StartingBalance = Convert.ToDecimal(startingBalance),
                CurrentBalance = Convert.ToDecimal(startingBalance),
                LowBalanceLevel = Convert.ToDecimal(warningBalance),
                Name = bankName,
                OwnerId = User.Identity.GetUserId()


            };
            db.BankAccounts.Add(newBank);
            db.SaveChanges();

            var newCategory = new Category
            {
                HouseholdId = newHouse.Id,
                Name = categoryName,
                Description = "Should have entered description in wizard",
                TargetAmount = 600
                
            };
            db.Categories.Add(newCategory);
            db.SaveChanges();

            var newItem = new CategoryItem
            {
                CategoryId = newCategory.Id,
                Name = itemName,
                Description = "",

            };
            db.CategoryItems.Add(newItem);
            db.SaveChanges();

            //Redirect to Dashboard
            return RedirectToAction("Dashboard");

        }

        // GET: Households/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Household household = db.Households.Find(id);
            if (household == null)
            {
                return HttpNotFound();
            }
            return View(household);
        }

        // POST: Households/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Created,Name,Greeting")] Household household)
        {
            if (ModelState.IsValid)
            {
                db.Entry(household).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(household);
        }

        // GET: Households/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Household household = db.Households.Find(id);
            if (household == null)
            {
                return HttpNotFound();
            }
            return View(household);
        }

        // POST: Households/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Household household = db.Households.Find(id);
            db.Households.Remove(household);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}


    //$.ajax({
    //type: "Post",
    //        url: '@Url.Action("GetCategoryChartData", "Charts")',
    //        dataType: "json"

    //    }).then(function (response) {
    //new Morris.Bar({
    //            element: 'cat1Chart',
    //            data: [response.Data],
    //            xkey: 0,
    //            ykeys: response.YKeys,
    //            labels: response.Labels,
    //            barColors: response.BarColors,
    //            gridTextSize: 11,
    //            hideHover: 'auto',
    //            resize: true
    //        });

    //    });

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@using Microsoft.AspNet.Identity
@using Carreno_Financial_Portal.Models

@model Carreno_Financial_Portal.Models.Household

<div class="container-fluid">
    <div class="row">
        <div class="col-12 col-sm-6 col-lg-4">
            <div class="card card primary card-outline">
                <div class="card-header p-0 pt-1 border-bottom-0">
                    <h1 style="text-align:center"> Houshold setup</h1>
                    <ul class="nav nav-tabs" id="custom-tabs-two-tab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="home-tab" data-toggle="pill" href="#group-section" role="tab" arial-controls="group-section" arial-selected="true">Group</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="bank-tab" data-toggle="pill" href="#bank-section" role="tab" arial-controls="bank-section" arial-selected="false">Bank</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="cat-tab" data-toggle="pill" href="#category-section" role="tab" arial-controls="category-section" arial-selected="false">Category</a>
                        </li>


                    </ul>
                </div>


                @using (Html.BeginForm("Create", "Households", FormMethod.Post, new { id = "userForm" }))
                {
                    @Html.AntiForgeryToken()
                    <div class="card-body">
                        <div class="tab-content" id="custom-tabs-two-tabcontent">
                            <div class="tab-pane fade active show" id="group-section" role="tabpanel" arial-labelledby="home-tab">
                                <p class="login-box-msg">Create Group</p>
                                <div class="form-horizontal">
                                    <div class="input-group mb-3">
                                        <input class="form-control input-lg" placeholder="House Name" type="text" name="houseName" id="houseName">
                                        <div class="input-group-append">
                                            <div class="input-group-text">
                                                <span class="fa fa-user">

                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="input-group mb-3">
                                        <input class="form-control input-lg" placeholder="House Greeting" type="text" name="greeting" id="greeting">
                                        <div class="input-group-append">
                                            <div class="input-group-text">
                                                <span class="fa fa-user">

                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">

                                        <div class="col-12">
                                            <a class="btn btn-primary btn-block btn-flat" style="color: white" onclick="bankTab()">
                                                Next
                                            </a>
                                        </div>

                                    </div>

                                </div>
                            </div>
                            <div class="tab-pane fade" id="bank-section" role="tabpanel" arial-labelledby="bank-tab">
                                <p class="login-box-msg">Bank Account Information</p>
                                <div class="form-horizontal">
                                    <div class="input-group mb-3">
                                        <input class="form-control input-lg" placeholder="Enter Bank Name" type="text" name="bankName" id="bankName">
                                        <div class="input-group-append">
                                            <div class="input-group-text">
                                                <span class="fa fa-bank">

                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="input-group mb-3">
                                        @*<input class="form-control input-lg" placeholder="" type="text" name="Name" id="Name">*@
                                        @Html.DropDownList("AccountType", null, new { @class = "form-control" })
                                        <div class="input-group-append">
                                            <div class="input-group-text">
                                                <span class="fa fa-tag">

                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="input-group mb-3">
                                        <input class="form-control input-lg" placeholder="Enter Starting Balance" type="text" name="startingBalance" id="startingBalance">
                                        <div class="input-group-append">
                                            <div class="input-group-text">
                                                <span class="fa fa-user">

                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="input-group mb-3">
                                        <input class="form-control input-lg" placeholder="Enter Warning Balance" type="text" name="warningBalance" id="warningBalance">
                                        <div class="input-group-append">
                                            <div class="input-group-text">
                                                <span class="fa fa-user">

                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">

                                        <div class="col-12">
                                            <a class="btn btn-primary btn-block btn-flat" style="color: white" onclick="categoryTab()">
                                                Next
                                            </a>
                                        </div>

                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane fade" id="category-section" role="tabpanel" arial-labelledby="bank-tab">
                                <p class="login-box-msg">Category/Item</p>
                                <div class="form-horizontal">
                                    <div class="input-group mb-3">
                                        <input class="form-control input-lg" placeholder="Category Name" type="text" name="categoryName" id="categoryName">
                                        <div class="input-group-append">
                                            <div class="input-group-text">
                                                <span class="fa fa-list">

                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="input-group mb-3">
                                        <input class="form-control input-lg" placeholder="Category Item" type="text" name="itemName" id="itemName">
                                        <div class="input-group-append">
                                            <div class="input-group-text">
                                                <span class="fa fa-user">

                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">

                                        <div class="col-12">
                                            <a class="btn btn-primary btn-block btn-flat" style="color: white" onclick="submitForm()">
                                                Finish
                                            </a>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@section scripts {

    <script>
    function bankTab() {
    $("#bank-tab").click();
    }
    function categoryTab() {
    $("#cat-tab").click();
    }
    function submitForm() {
    $("#userForm").submit();
    }


    </script>


}